# Generated by Django 4.2.17 on 2025-01-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='suggestor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='suggestor',
            name='password',
        ),
        migrations.AddField(
            model_name='book',
            name='purchase_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
