# Generated by Django 4.2.17 on 2025-01-12 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_remove_suggestor_email_remove_suggestor_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'Genres'},
        ),
        migrations.AddField(
            model_name='book',
            name='suggestor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hello.suggestor'),
        ),
    ]
