# Generated by Django 4.2.17 on 2025-01-12 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_genre_options_book_suggestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.DeleteModel(
            name='MonthlyBook',
        ),
    ]
