# Generated by Django 4.2.17 on 2025-01-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_book_date_delete_monthlybook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='purchase_link',
            new_name='amazon_link',
        ),
        migrations.AddField(
            model_name='book',
            name='bn_link',
            field=models.URLField(null=True),
        ),
    ]
